"""add offline emergency passport and green journey

Revision ID: 20260901_0007
Revises: 20260901_0006
Create Date: 2026-09-02 00:20:02.632754
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260901_0007"
down_revision: str | None = "20260901_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emergency_bulletins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "severity IN ('INFO', 'WARNING', 'CRITICAL')",
            name=op.f("ck_emergency_bulletins_valid_severity"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_emergency_bulletins_time_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_bulletins")),
        sa.UniqueConstraint("code", name=op.f("uq_emergency_bulletins_code")),
    )
    op.create_table(
        "green_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("points_award", sa.Integer(), nullable=False),
        sa.Column("evidence_hint", sa.String(length=300), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('TRANSPORT', 'REFILL', 'CULTURE', 'RECYCLE')",
            name=op.f("ck_green_tasks_valid_kind"),
        ),
        sa.CheckConstraint("points_award > 0", name=op.f("ck_green_tasks_points_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_green_tasks")),
        sa.UniqueConstraint("code", name=op.f("uq_green_tasks_code")),
    )
    op.create_table(
        "offline_packs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("etag", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > published_at",
            name=op.f("ck_offline_packs_expiry_after_publish"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_offline_packs_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_packs")),
        sa.UniqueConstraint("etag", name=op.f("uq_offline_packs_etag")),
        sa.UniqueConstraint("version", name=op.f("uq_offline_packs_version")),
    )
    op.create_table(
        "device_sync_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("cursor", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_client_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("cursor >= 0", name=op.f("ck_device_sync_states_cursor_nonnegative")),
        sa.CheckConstraint(
            "last_client_version >= 0",
            name=op.f("ck_device_sync_states_client_version_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_device_sync_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_sync_states")),
        sa.UniqueConstraint("user_id", "device_id", name="uq_device_sync_states_device"),
    )
    op.create_table(
        "green_task_completions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("evidence", sa.String(length=500), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points_awarded > 0", name=op.f("ck_green_task_completions_points_positive")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["green_tasks.id"],
            name=op.f("fk_green_task_completions_task_id_green_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_green_task_completions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_green_task_completions")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_green_task_completions_user_idempotency"
        ),
        sa.UniqueConstraint("user_id", "task_id", name="uq_green_task_completions_user_task"),
    )
    op.create_table(
        "journey_idempotency_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('DUPLICATE_REJECTED')",
            name=op.f("ck_journey_idempotency_receipts_valid_outcome"),
        ),
        sa.CheckConstraint(
            "scope IN ('PASSPORT_STAMP', 'GREEN_TASK')",
            name=op.f("ck_journey_idempotency_receipts_valid_scope"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_journey_idempotency_receipts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journey_idempotency_receipts")),
        sa.UniqueConstraint(
            "user_id", "scope", "idempotency_key", name="uq_journey_idempotency_receipts_key"
        ),
    )
    op.create_table(
        "offline_assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pack_id", sa.Uuid(), nullable=False),
        sa.Column("asset_key", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("required", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_offline_assets_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["pack_id"],
            ["offline_packs.id"],
            name=op.f("fk_offline_assets_pack_id_offline_packs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_assets")),
        sa.UniqueConstraint("pack_id", "asset_key", name="uq_offline_assets_key"),
    )
    op.create_table(
        "offline_mutations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=100), nullable=False),
        sa.Column("client_mutation_id", sa.String(length=128), nullable=False),
        sa.Column("client_version", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("server_cursor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('UPSERT', 'DELETE')", name=op.f("ck_offline_mutations_valid_operation")
        ),
        sa.CheckConstraint(
            "client_version > 0", name=op.f("ck_offline_mutations_client_version_positive")
        ),
        sa.CheckConstraint(
            "server_cursor > 0", name=op.f("ck_offline_mutations_server_cursor_positive")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_offline_mutations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_mutations")),
        sa.UniqueConstraint(
            "user_id", "device_id", "client_mutation_id", name="uq_offline_mutations_client_id"
        ),
        sa.UniqueConstraint("user_id", "server_cursor", name="uq_offline_mutations_server_cursor"),
    )
    op.create_index(
        "ix_offline_mutations_user_cursor",
        "offline_mutations",
        ["user_id", "server_cursor"],
        unique=False,
    )
    op.create_table(
        "user_sync_counters",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("next_cursor", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sync_counters_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_sync_counters")),
    )
    op.create_table(
        "emergency_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("instructions", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["route_nodes.id"],
            name=op.f("fk_emergency_resources_node_id_route_nodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emergency_resources")),
        sa.UniqueConstraint("code", name=op.f("uq_emergency_resources_code")),
    )
    op.create_table(
        "passport_stamp_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("points_award", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "points_award > 0", name=op.f("ck_passport_stamp_definitions_points_positive")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["route_nodes.id"],
            name=op.f("fk_passport_stamp_definitions_node_id_route_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passport_stamp_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_passport_stamp_definitions_code")),
    )
    op.create_table(
        "sos_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sos_no", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("latitude_e6", sa.Integer(), nullable=True),
        sa.Column("longitude_e6", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "kind IN ('MEDICAL', 'LOST', 'SAFETY', 'OTHER')",
            name=op.f("ck_sos_requests_valid_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('DEMO_RECEIVED', 'ACKNOWLEDGED', 'RESOLVED')",
            name=op.f("ck_sos_requests_valid_status"),
        ),
        sa.CheckConstraint(
            "(latitude_e6 IS NULL AND longitude_e6 IS NULL) OR "
            "(latitude_e6 IS NOT NULL AND longitude_e6 IS NOT NULL)",
            name=op.f("ck_sos_requests_coordinate_pair"),
        ),
        sa.CheckConstraint(
            "latitude_e6 IS NULL OR (latitude_e6 >= -90000000 AND latitude_e6 <= 90000000)",
            name=op.f("ck_sos_requests_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude_e6 IS NULL OR (longitude_e6 >= -180000000 AND longitude_e6 <= 180000000)",
            name=op.f("ck_sos_requests_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["route_nodes.id"],
            name=op.f("fk_sos_requests_node_id_route_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sos_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sos_requests")),
        sa.UniqueConstraint("sos_no", name=op.f("uq_sos_requests_sos_no")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_sos_requests_user_idempotency_key"
        ),
    )
    op.create_index(
        "ix_sos_requests_user_created", "sos_requests", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "passport_stamps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("points_awarded > 0", name=op.f("ck_passport_stamps_points_positive")),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["passport_stamp_definitions.id"],
            name=op.f("fk_passport_stamps_definition_id_passport_stamp_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_passport_stamps_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passport_stamps")),
        sa.UniqueConstraint("user_id", "definition_id", name="uq_passport_stamps_user_definition"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_passport_stamps_user_idempotency"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passport_stamps")
    op.drop_index("ix_sos_requests_user_created", table_name="sos_requests")
    op.drop_table("sos_requests")
    op.drop_table("passport_stamp_definitions")
    op.drop_table("emergency_resources")
    op.drop_table("user_sync_counters")
    op.drop_index("ix_offline_mutations_user_cursor", table_name="offline_mutations")
    op.drop_table("offline_mutations")
    op.drop_table("offline_assets")
    op.drop_table("journey_idempotency_receipts")
    op.drop_table("green_task_completions")
    op.drop_table("device_sync_states")
    op.drop_table("offline_packs")
    op.drop_table("green_tasks")
    op.drop_table("emergency_bulletins")
    # ### end Alembic commands ###
