"""add commerce engagement support groups and facilities

Revision ID: 20260901_0006
Revises: 20260901_0005
Create Date: 2026-09-01 23:16:38.372765
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260901_0006"
down_revision: str | None = "20260901_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faqs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("question", sa.String(length=300), nullable=False),
        sa.Column("answer", sa.String(length=2000), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faqs")),
        sa.UniqueConstraint("code", name=op.f("uq_faqs_code")),
    )
    op.create_table(
        "rewards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("points_cost", sa.Integer(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("points_cost > 0", name=op.f("ck_rewards_points_positive")),
        sa.CheckConstraint("stock >= 0", name=op.f("ck_rewards_stock_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rewards")),
        sa.UniqueConstraint("code", name=op.f("uq_rewards_code")),
    )
    op.create_table(
        "shop_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_shop_categories_code")),
    )
    op.create_table(
        "carts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_carts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
        sa.UniqueConstraint("user_id", name=op.f("uq_carts_user_id")),
    )
    op.create_table(
        "content_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("share_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_ref", sa.String(length=128), nullable=False),
        sa.Column("caption", sa.String(length=500), nullable=False),
        sa.Column("verified", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "points_awarded >= 0", name=op.f("ck_content_shares_points_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_content_shares_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_shares")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_content_shares_user_idempotency_key"
        ),
        sa.UniqueConstraint("user_id", "share_key", name="uq_content_shares_user_share_key"),
    )
    op.create_table(
        "delivery_addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("province", sa.String(length=80), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("address_line", sa.String(length=300), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_delivery_addresses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_addresses")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_no", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolution", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "category IN ('FEEDBACK', 'COMPLAINT', 'SUGGESTION')",
            name=op.f("ck_feedback_valid_category"),
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH')", name=op.f("ck_feedback_valid_priority")
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')",
            name=op.f("ck_feedback_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_feedback_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("ticket_no", name=op.f("uq_feedback_ticket_no")),
    )
    op.create_index(
        "ix_feedback_status_created", "feedback", ["status", "created_at"], unique=False
    )
    op.create_table(
        "point_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name=op.f("ck_point_accounts_balance_nonnegative")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_point_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_point_accounts")),
    )
    op.create_table(
        "point_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_type IN ('EARN', 'SPEND', 'REFUND')",
            name=op.f("ck_point_ledger_entries_valid_entry_type"),
        ),
        sa.CheckConstraint(
            "balance_after >= 0", name=op.f("ck_point_ledger_entries_balance_nonnegative")
        ),
        sa.CheckConstraint("delta <> 0", name=op.f("ck_point_ledger_entries_delta_nonzero")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_point_ledger_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_point_ledger_entries")),
        sa.UniqueConstraint(
            "user_id", "source_type", "source_id", "entry_type", name="uq_point_ledger_source"
        ),
    )
    op.create_index(
        "ix_point_ledger_user_created",
        "point_ledger_entries",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("points_price", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.CheckConstraint(
            "points_price IS NULL OR points_price > 0",
            name=op.f("ck_products_points_price_positive"),
        ),
        sa.CheckConstraint("price_cents >= 0", name=op.f("ck_products_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["shop_categories.id"],
            name=op.f("fk_products_category_id_shop_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(
        "ix_products_category_active", "products", ["category_id", "is_active"], unique=False
    )
    op.create_table(
        "redemptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("redemption_no", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reward_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('CONFIRMED', 'CANCELLED')", name=op.f("ck_redemptions_valid_status")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_redemptions_quantity_positive")),
        sa.CheckConstraint("total_points > 0", name=op.f("ck_redemptions_points_positive")),
        sa.ForeignKeyConstraint(
            ["reward_id"],
            ["rewards.id"],
            name=op.f("fk_redemptions_reward_id_rewards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_redemptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_redemptions")),
        sa.UniqueConstraint("redemption_no", name=op.f("uq_redemptions_redemption_no")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_redemptions_user_id_idempotency_key"
        ),
    )
    op.create_table(
        "support_conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_no", sa.String(length=48), nullable=False),
        sa.Column("tourist_user_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_support_user_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('DEMO_BOT', 'LIVE')", name=op.f("ck_support_conversations_valid_mode")
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'CLOSED')", name=op.f("ck_support_conversations_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_support_user_id"],
            ["users.id"],
            name=op.f("fk_support_conversations_assigned_support_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tourist_user_id"],
            ["users.id"],
            name=op.f("fk_support_conversations_tourist_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_conversations")),
        sa.UniqueConstraint(
            "conversation_no", name=op.f("uq_support_conversations_conversation_no")
        ),
    )
    op.create_index(
        "ix_support_conversations_tourist_created",
        "support_conversations",
        ["tourist_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("discount_bps", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.CheckConstraint(
            "discount_bps > 0 AND discount_bps < 10000",
            name=op.f("ck_campaigns_discount_bps_range"),
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_campaigns_time_order")),
        sa.CheckConstraint(
            "product_id IS NOT NULL OR category_id IS NOT NULL",
            name=op.f("ck_campaigns_target_required"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["shop_categories.id"],
            name=op.f("fk_campaigns_category_id_shop_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_campaigns_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("code", name=op.f("uq_campaigns_code")),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cart_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("added_price_cents", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("added_price_cents >= 0", name=op.f("ck_cart_items_price_nonnegative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cart_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_cart_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
        sa.UniqueConstraint("cart_id", "product_id", name="uq_cart_items_product"),
    )
    op.create_table(
        "facility_pois",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=800), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("accessible", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("wheelchair_ok", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("stroller_accessible", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("baby_care", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("open_status", sa.String(length=24), server_default="OPEN", nullable=False),
        sa.Column("source", sa.String(length=40), server_default="curated_demo", nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["route_nodes.id"],
            name=op.f("fk_facility_pois_node_id_route_nodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facility_pois")),
        sa.UniqueConstraint("code", name=op.f("uq_facility_pois_code")),
    )
    op.create_table(
        "feedback_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_feedback_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback.id"],
            name=op.f("fk_feedback_events_feedback_id_feedback"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_events")),
    )
    op.create_table(
        "feedback_followups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_feedback_followups_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["feedback.id"],
            name=op.f("fk_feedback_followups_feedback_id_feedback"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_feedback_followups_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_followups")),
        sa.UniqueConstraint("feedback_id", name=op.f("uq_feedback_followups_feedback_id")),
    )
    op.create_table(
        "product_inventories",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("stock >= 0", name=op.f("ck_product_inventories_stock_nonnegative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_inventories_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_product_inventories")),
    )
    op.create_table(
        "shop_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_no", sa.String(length=48), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_address_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("payment_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("payment_reference", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING_PAYMENT', 'PAID', 'CANCELLED', 'EXPIRED')",
            name=op.f("ck_shop_orders_valid_status"),
        ),
        sa.CheckConstraint("discount_cents >= 0", name=op.f("ck_shop_orders_discount_nonnegative")),
        sa.CheckConstraint("points_awarded >= 0", name=op.f("ck_shop_orders_points_nonnegative")),
        sa.CheckConstraint("subtotal_cents >= 0", name=op.f("ck_shop_orders_subtotal_nonnegative")),
        sa.CheckConstraint("total_cents >= 0", name=op.f("ck_shop_orders_total_nonnegative")),
        sa.CheckConstraint("total_quantity > 0", name=op.f("ck_shop_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"],
            ["delivery_addresses.id"],
            name=op.f("fk_shop_orders_delivery_address_id_delivery_addresses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_shop_orders_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_orders")),
        sa.UniqueConstraint("order_no", name=op.f("uq_shop_orders_order_no")),
        sa.UniqueConstraint("payment_reference", name=op.f("uq_shop_orders_payment_reference")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_shop_orders_user_id_idempotency_key"
        ),
    )
    op.create_index(
        "ix_shop_orders_user_created", "shop_orders", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "support_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_user_id", sa.Uuid(), nullable=True),
        sa.Column("sender_key", sa.String(length=64), nullable=False),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.String(length=2000), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sender_type IN ('TOURIST', 'SUPPORT', 'BOT')",
            name=op.f("ck_support_messages_valid_sender_type"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_support_messages_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["support_conversations.id"],
            name=op.f("fk_support_messages_conversation_id_support_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name=op.f("fk_support_messages_sender_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "sender_key",
            "idempotency_key",
            name="uq_support_messages_sender_idempotency",
        ),
        sa.UniqueConstraint("conversation_id", "sequence", name="uq_support_messages_sequence"),
    )
    op.create_table(
        "travel_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("invite_code", sa.String(length=32), nullable=False),
        sa.Column("invite_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("itinerary_id", sa.Uuid(), nullable=True),
        sa.Column("share_itinerary", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("share_location", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("share_member_status", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_travel_groups_revision_positive")),
        sa.ForeignKeyConstraint(
            ["itinerary_id"],
            ["itineraries.id"],
            name=op.f("fk_travel_groups_itinerary_id_itineraries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_travel_groups_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_travel_groups")),
        sa.UniqueConstraint("invite_code", name=op.f("uq_travel_groups_invite_code")),
    )
    op.create_table(
        "group_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("share_location", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("share_status", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("latitude_e6", sa.Integer(), nullable=True),
        sa.Column("longitude_e6", sa.Integer(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('OWNER', 'MEMBER')", name=op.f("ck_group_members_valid_role")),
        sa.CheckConstraint(
            "status IN ('TOGETHER', 'MOVING', 'WAITING', 'LOST')",
            name=op.f("ck_group_members_valid_status"),
        ),
        sa.CheckConstraint(
            "latitude_e6 IS NULL OR (latitude_e6 >= -90000000 AND latitude_e6 <= 90000000)",
            name=op.f("ck_group_members_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude_e6 IS NULL OR (longitude_e6 >= -180000000 AND longitude_e6 <= 180000000)",
            name=op.f("ck_group_members_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["travel_groups.id"],
            name=op.f("fk_group_members_group_id_travel_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_members")),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_members_user"),
    )
    op.create_table(
        "meeting_points",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("meeting_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_meeting_points_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["travel_groups.id"],
            name=op.f("fk_meeting_points_group_id_travel_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["route_nodes.id"],
            name=op.f("fk_meeting_points_node_id_route_nodes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meeting_points")),
    )
    op.create_table(
        "shop_order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("product_name", sa.String(length=160), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("line_total_cents", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "line_total_cents >= 0", name=op.f("ck_shop_order_items_line_total_nonnegative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_shop_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_cents >= 0", name=op.f("ck_shop_order_items_unit_price_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_shop_order_items_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["shop_orders.id"],
            name=op.f("fk_shop_order_items_order_id_shop_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_shop_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shop_order_items")),
    )
    op.create_table(
        "lost_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_member_id", sa.Uuid(), nullable=False),
        sa.Column("last_seen_node_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'RESOLVED')", name=op.f("ck_lost_alerts_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["travel_groups.id"],
            name=op.f("fk_lost_alerts_group_id_travel_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_node_id"],
            ["route_nodes.id"],
            name=op.f("fk_lost_alerts_last_seen_node_id_route_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
            name=op.f("fk_lost_alerts_reporter_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_member_id"],
            ["group_members.id"],
            name=op.f("fk_lost_alerts_target_member_id_group_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lost_alerts")),
    )
    op.create_index(
        "ix_lost_alerts_group_status", "lost_alerts", ["group_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lost_alerts_group_status", table_name="lost_alerts")
    op.drop_table("lost_alerts")
    op.drop_table("shop_order_items")
    op.drop_table("meeting_points")
    op.drop_table("group_members")
    op.drop_table("travel_groups")
    op.drop_table("support_messages")
    op.drop_index("ix_shop_orders_user_created", table_name="shop_orders")
    op.drop_table("shop_orders")
    op.drop_table("product_inventories")
    op.drop_table("feedback_followups")
    op.drop_table("feedback_events")
    op.drop_table("facility_pois")
    op.drop_table("cart_items")
    op.drop_table("campaigns")
    op.drop_index("ix_support_conversations_tourist_created", table_name="support_conversations")
    op.drop_table("support_conversations")
    op.drop_table("redemptions")
    op.drop_index("ix_products_category_active", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_point_ledger_user_created", table_name="point_ledger_entries")
    op.drop_table("point_ledger_entries")
    op.drop_table("point_accounts")
    op.drop_index("ix_feedback_status_created", table_name="feedback")
    op.drop_table("feedback")
    op.drop_table("delivery_addresses")
    op.drop_table("content_shares")
    op.drop_table("carts")
    op.drop_table("shop_categories")
    op.drop_table("rewards")
    op.drop_table("faqs")
    # ### end Alembic commands ###
