"""Model imports used to populate SQLAlchemy metadata."""

from app.db.models.guide import (
    Attraction,
    ConflictCheck,
    CrowdSnapshot,
    Itinerary,
    ItineraryItem,
    Narration,
    PlanRun,
    RouteEdge,
    RouteNode,
)
from app.db.models.marketplace import (
    BundleComponent,
    Experience,
    ExperienceSession,
    FastPass,
    HospitalityOffer,
    HospitalityVenue,
    InventoryBucket,
    QueueCounter,
    QueueEntry,
    Reservation,
    ReservationAllocation,
    Review,
    UserScheduleLock,
)
from app.db.models.preference import TouristPreference
from app.db.models.refresh_session import RefreshSession
from app.db.models.role import Role, UserRole
from app.db.models.seed_record import SeedRecord
from app.db.models.ticketing import (
    DynamicPriceRule,
    ElectronicTicket,
    RefundRequest,
    RescheduleRequest,
    TicketInventory,
    TicketOrder,
    TicketOrderItem,
    TicketSlot,
    TicketType,
    TicketValidation,
)
from app.db.models.user import User

__all__ = [
    "Attraction",
    "BundleComponent",
    "ConflictCheck",
    "CrowdSnapshot",
    "DynamicPriceRule",
    "ElectronicTicket",
    "Experience",
    "ExperienceSession",
    "FastPass",
    "HospitalityOffer",
    "HospitalityVenue",
    "InventoryBucket",
    "Itinerary",
    "ItineraryItem",
    "Narration",
    "PlanRun",
    "QueueCounter",
    "QueueEntry",
    "RefreshSession",
    "RefundRequest",
    "RescheduleRequest",
    "Reservation",
    "ReservationAllocation",
    "Review",
    "Role",
    "RouteEdge",
    "RouteNode",
    "SeedRecord",
    "TicketInventory",
    "TicketOrder",
    "TicketOrderItem",
    "TicketSlot",
    "TicketType",
    "TicketValidation",
    "TouristPreference",
    "User",
    "UserRole",
    "UserScheduleLock",
]
