"""Model imports used to populate SQLAlchemy metadata."""

from app.db.models.commerce import (
    Campaign,
    Cart,
    CartItem,
    ContentShare,
    DeliveryAddress,
    PointAccount,
    PointLedgerEntry,
    Product,
    ProductInventory,
    Redemption,
    Reward,
    ShopCategory,
    ShopOrder,
    ShopOrderItem,
)
from app.db.models.engagement import (
    FAQ,
    FacilityPOI,
    Feedback,
    FeedbackEvent,
    FeedbackFollowUp,
    GroupMember,
    LostAlert,
    MeetingPoint,
    SupportConversation,
    SupportMessage,
    TravelGroup,
)
from app.db.models.guide import (
    Attraction,
    ConflictCheck,
    CrowdSnapshot,
    Itinerary,
    ItineraryItem,
    Narration,
    PlanRun,
    RouteEdge,
    RouteNode,
)
from app.db.models.marketplace import (
    BundleComponent,
    Experience,
    ExperienceSession,
    FastPass,
    HospitalityOffer,
    HospitalityVenue,
    InventoryBucket,
    QueueCounter,
    QueueEntry,
    Reservation,
    ReservationAllocation,
    Review,
    UserScheduleLock,
)
from app.db.models.preference import TouristPreference
from app.db.models.refresh_session import RefreshSession
from app.db.models.role import Role, UserRole
from app.db.models.seed_record import SeedRecord
from app.db.models.ticketing import (
    DynamicPriceRule,
    ElectronicTicket,
    RefundRequest,
    RescheduleRequest,
    TicketInventory,
    TicketOrder,
    TicketOrderItem,
    TicketSlot,
    TicketType,
    TicketValidation,
)
from app.db.models.user import User

__all__ = [
    "FAQ",
    "Attraction",
    "BundleComponent",
    "Campaign",
    "Cart",
    "CartItem",
    "ConflictCheck",
    "ContentShare",
    "CrowdSnapshot",
    "DeliveryAddress",
    "DynamicPriceRule",
    "ElectronicTicket",
    "Experience",
    "ExperienceSession",
    "FacilityPOI",
    "FastPass",
    "Feedback",
    "FeedbackEvent",
    "FeedbackFollowUp",
    "GroupMember",
    "HospitalityOffer",
    "HospitalityVenue",
    "InventoryBucket",
    "Itinerary",
    "ItineraryItem",
    "LostAlert",
    "MeetingPoint",
    "Narration",
    "PlanRun",
    "PointAccount",
    "PointLedgerEntry",
    "Product",
    "ProductInventory",
    "QueueCounter",
    "QueueEntry",
    "Redemption",
    "RefreshSession",
    "RefundRequest",
    "RescheduleRequest",
    "Reservation",
    "ReservationAllocation",
    "Review",
    "Reward",
    "Role",
    "RouteEdge",
    "RouteNode",
    "SeedRecord",
    "ShopCategory",
    "ShopOrder",
    "ShopOrderItem",
    "SupportConversation",
    "SupportMessage",
    "TicketInventory",
    "TicketOrder",
    "TicketOrderItem",
    "TicketSlot",
    "TicketType",
    "TicketValidation",
    "TouristPreference",
    "TravelGroup",
    "User",
    "UserRole",
    "UserScheduleLock",
]
